# Generated by Django 3.2.6 on 2021-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210819_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='color',
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='colors',
            field=models.ManyToManyField(related_name='phones', to='phones.ColorModel'),
        ),
    ]
