# Generated by Django 3.2.6 on 2021-08-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20210819_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='GPU',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='RAM',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='built_in_memory',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='main_lens',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='number_of_processor_cores',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='processor',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccessoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='accessories')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='phones.brandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='phones.categorymodel', verbose_name='category')),
                ('colors', models.ManyToManyField(related_name='accessories', to='phones.ColorModel')),
            ],
            options={
                'verbose_name': 'accessor',
                'verbose_name_plural': 'accessories',
            },
        ),
    ]
