# Generated by Django 3.2.6 on 2021-08-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20210820_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodel',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='short_description',
            field=models.CharField(default=None, max_length=555),
            preserve_default=False,
        ),
    ]
