# Generated by Django 3.2.6 on 2021-08-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20210820_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemodel',
            old_name='long_description',
            new_name='long_descriptions',
        ),
    ]
