# Generated by Django 3.2.6 on 2021-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_rename_long_descriptions_phonemodel_long_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoriesmodel',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='accessoriesmodel',
            name='short_description',
            field=models.CharField(default=None, max_length=555),
            preserve_default=False,
        ),
    ]
