# Generated by Django 3.2.6 on 2021-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computermodel',
            old_name='main_lens',
            new_name='CPU',
        ),
        migrations.AddField(
            model_name='computermodel',
            name='SSD',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
