# Generated by Django 3.2.6 on 2021-08-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20210820_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computermodel',
            options={'verbose_name': 'Computer', 'verbose_name_plural': 'computers'},
        ),
    ]
