# Generated by Django 3.2.6 on 2021-08-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_alter_computermodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computermodel',
            name='processor',
        ),
    ]
